<?php

/**
 * @file
 * A block module that displays recent blog and forum posts.
 */

function fgrtournaments_help($path, $arg) {
	switch ($path) {
    case "admin/help#fgrtournaments":
      return '' . t("Displays tournaments FGR") . '';
      break;
  }
}

/**
 * Implements hook_block_info().
 */
function fgrtournaments_block_info() {
  $blocks['fgrtournaments'] = array(
    'info' => t('FGR Tournaments'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}