<?php

/**
 * @file
 * A block module that displays recent blog and forum posts.
 */

function fgrtournaments_help($path, $arg) {
	switch ($path) {
    case "admin/help#fgrtournaments":
      return '' . t("Displays tournaments FGR") . '';
      break;
  }
}

/**
 * Implements hook_block_info().
 */
function fgrtournaments_block_info() {
  $blocks['fgrtournaments'] = array(
    'info' => t('FGR Tournaments'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

/**
 *
 * @return Last tournaments for link.
 */
function fgrtournaments_contents(){
  module_load_include('inc', 'fgrtournaments', 'fgrtournaments.api');
  return get_last_tournaments();
}

/**
 * Implements hook_block_view().
 *
 * Prepares the contents of the block.
 */
function fgrtournaments_block_view($delta = '') {
  switch ($delta) {
    case 'fgrtournaments':
      $result = fgrtournaments_contents();
      insert_new_tournaments_as_node($result);
      $items = array();
      foreach ($result as $node) {
        $items[] = array(
          'data' => l($node['title'], 'node/' . $node['id']),
        );
      }
      if (empty($items)) {
        $block['content'] = t('No tournaments available.');
      }
      else {
        $block['content'] = theme('item_list', array(
          'items' => $items));
      }
      return $block;
  }
}

/**
 * @param $tournaments - requested list of tournaments from Statistics service
 *
 * Inserts new tournaments as nodes and tournament ids from Statistics service
 */
function insert_new_tournaments_as_node($tournaments) {

}