<?php

/**
 * @file
 * A block module that displays recent blog and forum posts.
 */

function fgrtournament_help($path, $arg) {
  switch ($path) {
    case "admin/help#fgrtournament":
      return '' . t("Displays tournament bracket") . '';
      break;
  }
}

/**
 * Implements hook_node_info().
 */
function fgrtournament_node_info() {
  $items = array(
      'fgrtournament' => array(
          'name' => t('FGR tournament bracket'),
          'base' => 'node_content',
          'description' => t('Displays tournament bracket.'),
          'help' => 'Displays tournament bracket.',
      ),
  );
  return $items;
}

/**
 * Implements hook_load().
 */
function fgrtournament_load($nodes)
{
    $result = db_query('SELECT * FROM {fgrtournament} WHERE nid IN (:nids)', array(':nids' => array_keys($nodes)));
    foreach ($result as $fields) {
        $nid = $fields->nid;
        foreach ($fields as $key => $value) {
            if (!isset($nodes[$nid]->$key)) {
                $nodes[$nid]->$key = $value;
                if($key == 'id') {
                    fill_tournament_node($nodes[$nid], $value);
                }
            }
        }
    }
}

function fill_tournament_node($node, $id) {
    module_load_include('inc', 'fgrtournament', 'fgrtournament.api');
    $additional_tournament_data = get_tournament_by_id($id);

}

/**
 * Implements hook_block_view().
 *
 * Prepares the contents of the block.
 */
/**
 * Implements hook_node_view().
 */
function fgrtournament_node_view($node, $view_mode, $langcode)
{
    switch ($node->type) {
        case 'fgrtournament':
            $node->content['extra_link'] = array(
                '#weight' => 10,
                '#theme' => 'link',
                '#path' => 'path',
                '#text' => t('An extra link'),
                '#options' => array(
                    'attributes' => array(),
                    'html' => FALSE
                ),
            );
            break;
    }
}
