<?php

/**
 * @file
 * A block module that displays recent blog and forum posts.
 */
function fgrreferee_help($path, $arg) {
  switch ($path) {
    case "admin/help#fgrreferee":
      return '' . t("Displays fgr referees") . '';
      break;
  }
}

/**
 * Implements hook_node_info().
 */
function fgrreferee_node_info() {
  $items = array(
      'fgrreferee' => array(
          'name' => t('FGR referee'),
          'base' => 'node_content',
          'description' => t('Displays FGR referees.'),
          'help' => 'Displays FGR referees.',
      ),
  );
  return $items;
}

/**
 * Implements hook_node_view().
 */
function fgrreferee_node_view($node, $view_mode, $langcode)
{
    module_load_include('inc', 'fgrreferee', 'fgrreferee.api');
    switch ($node->type) {
        case 'fgrreferee':
            if(isset($_GET['referee_id'])) {
                $referee_id = $_GET['referee_id'];
                $referee_data = get_referee_by_id($referee_id);
                $node->content['fgrreferee'] = array(
                    "#markup" => theme('fgrreferee', array('fgrreferee' => $referee_data, 'node' => $node))
                );
            } else {
                $search_query = '';
                if(isset($GET['search_query'])) {
                    $search_query = $GET['search_query'];
                }
                $seasons = get_all_seasons();
                $result = get_fgr_referees($search_query);
                $node->content['fgrreferee_list'] = array(
                    "#markup" => theme('fgrreferee_list', array('fgrreferee_list' => $result, 'node' => $node, 'seasons' => $seasons))
                );
            }
            break;
    }
}

/**
 * Implements hook_theme();
*/
function fgrreferee_theme() {
    return array(
        'fgrreferee_list' => array(
            'variables' => array('fgrreferee_list' => NULL, 'node' => NULL, 'game_node_id' => NULL, 'seasons' => NULL),
            'template' => 'templates/fgrreferee-list',
            'file' => 'fgrreferee.pages.inc',
        ),
        'fgrreferee' => array(
            'variables' => array('fgrreferee' => NULL, 'node' => NULL, 'game_node_id' => NULL),
            'template' => 'templates/fgrreferee',
            'file' => 'fgrreferee.pages.inc',
        )
    );
}