<?php

/**
 * @file
 * A block module that displays recent blog and forum posts.
 */
function fgrreferee_help($path, $arg) {
  switch ($path) {
    case "admin/help#fgrreferee":
      return '' . t("Displays fgr referees") . '';
      break;
  }
}

/**
 * Implements hook_node_info().
 */
function fgrreferee_node_info() {
  $items = array(
      'fgrreferee' => array(
          'name' => t('FGR referee'),
          'base' => 'node_content',
          'description' => t('Displays FGR referees.'),
          'help' => 'Displays FGR referees.',
      ),
  );
  return $items;
}

/**
 * Implements hook_node_view().
 */
function fgrreferee_node_view($node, $view_mode, $langcode)
{
    module_load_include('inc', 'fgrreferee', 'fgrreferee.api');
    switch ($node->type) {
        case 'fgrreferee':
            $crumbs = array();
            if(isset($_GET['crumbs'])) {
                $crumbs_buff = explode(';', $_GET['crumbs']);
                foreach($crumbs_buff as $crumb) {
                    $buff = explode(':', $crumb);
                    array_push($crumbs, array(
                        'title' => $buff[0],
                        'ref' => $buff[1]
                    ));
                }
            }
            if(isset($_GET['referee_id'])) {
                $referee_id = $_GET['referee_id'];
                $referee_data = get_referee_by_id($referee_id);
                $view_type = 'competitions';
                if(isset($_GET['type'])) {
                    $view_type = $_GET['type'];
                }
                switch($view_type) {
                    case 'competitions':
                        if($referee_data['type'] == 'inspector') {
                            $node->content['fgrreferee_inspector_competitions'] = array(
                                "#markup" => theme('fgrreferee_inspector_competitions', array('fgrreferee' => $referee_data, 'node' => $node, 'crumbs' => $crumbs))
                            );
                            break;
                        } else {
                            $node->content['fgrreferee_competitions'] = array(
                                "#markup" => theme('fgrreferee_competitions', array('fgrreferee' => $referee_data, 'node' => $node, 'crumbs' => $crumbs))
                            );
                            break;
                        }
                    case 'games':
                        if($referee_data['type'] == 'inspector') {
                            $node->content['fgrreferee_inspector_games'] = array(
                                "#markup" => theme('fgrreferee_inspector_games', array('fgrreferee' => $referee_data, 'node' => $node, 'crumbs' => $crumbs))
                            );
                            break;
                        } else {
                            $node->content['fgrreferee_games'] = array(
                                "#markup" => theme('fgrreferee_games', array('fgrreferee' => $referee_data, 'node' => $node, 'crumbs' => $crumbs))
                            );
                            break;
                        }
                }
            } else {
                $top = (isset($_GET['top'])) ? $_GET['top'] : 20;
                $skip = (isset($_GET['skip'])) ? $_GET['skip'] : 0;
                $seasons = get_all_seasons();
                $result = get_fgr_referees(array(
                    'name' => (isset($_GET['name'])) ? $_GET['name'] : NULL,
                    'sername' => (isset($_GET['sername'])) ? $_GET['sername'] : NULL,
                    'second_name' => (isset($_GET['second_name'])) ? $_GET['second_name'] : NULL,
                    'show_all' => (isset($_GET['show_all'])) ? $_GET['show_all'] : NULL,
                    'competition_id' => (isset($_GET['competition_id'])) ? $_GET['competition_id'] : NULL,
                    'top' => $top,
                    'skip' => $skip
                ));
                $node->content['fgrreferee_list'] = array(
                    "#markup" => theme('fgrreferee_list', array('fgrreferee_list' => $result, 'node' => $node, 'seasons' => $seasons, 'top' => $top, 'skip' => $skip))
                );
            }
            break;
    }
}

/**
 * Implements hook_theme();
*/
function fgrreferee_theme() {
    return array(
        'fgrreferee_list' => array(
            'variables' => array('fgrreferee_list' => NULL, 'node' => NULL, 'game_node_id' => NULL, 'seasons' => NULL, 'top' => 20, 'skip' => 0),
            'template' => 'templates/fgrreferee-list',
            'file' => 'fgrreferee.pages.inc',
        ),
        'fgrreferee_competitions' => array(
            'variables' => array('fgrreferee' => NULL, 'node' => NULL, 'game_node_id' => NULL, 'crumbs' => NULL),
            'template' => 'templates/fgrreferee-competitions',
            'file' => 'fgrreferee.pages.inc',
        ),
        'fgrreferee_games' => array(
            'variables' => array('fgrreferee' => NULL, 'node' => NULL, 'game_node_id' => NULL, 'crumbs' => NULL),
            'template' => 'templates/fgrreferee-games',
            'file' => 'fgrreferee.pages.inc',
        ),
        'fgrreferee_inspector_competitions' => array(
            'variables' => array('fgrreferee' => NULL, 'node' => NULL, 'game_node_id' => NULL, 'crumbs' => NULL),
            'template' => 'templates/fgrreferee-inspector-competitions',
            'file' => 'fgrreferee.pages.inc',
        ),
        'fgrreferee_inspector_games' => array(
            'variables' => array('fgrreferee' => NULL, 'node' => NULL, 'game_node_id' => NULL, 'crumbs' => NULL),
            'template' => 'templates/fgrreferee-inspector-games',
            'file' => 'fgrreferee.pages.inc',
        )
    );
}