<?php

/**
 * @file
 * A block module that displays recent blog and forum posts.
 */
function fgrteam_help($path, $arg) {
  switch ($path) {
    case "admin/help#fgrteam":
      return '' . t("Displays fgr teams") . '';
      break;
  }
}

/**
 * Implements hook_node_info().
 */
function fgrteam_node_info() {
  $items = array(
      'fgrteam' => array(
          'name' => t('FGR team'),
          'base' => 'node_content',
          'description' => t('Displays FGR team.'),
          'help' => 'Displays FGR team.',
      ),
  );
  return $items;
}

/**
 * Implements hook_node_view().
 */
function fgrteam_node_view($node, $view_mode, $langcode)
{
    module_load_include('inc', 'fgrteam', 'fgrteam.api');
    switch ($node->type) {
        case 'fgrteam':
            $crumbs = array();
            if(isset($_GET['crumbs'])) {
                $crumbs_buff = explode(';', $_GET['crumbs']);
                foreach($crumbs_buff as $crumb) {
                    $buff = explode(':', $crumb);
                    array_push($crumbs, array(
                        'title' => $buff[0],
                        'ref' => $buff[1]
                    ));
                }
            }
            if(isset($_GET['team_id'])) {
                drupal_add_js(drupal_get_path('module', 'fgrteam') . '/js/sorttable.js');
                drupal_add_js(drupal_get_path('module', 'fgrteam') . '/js/jquery-ui.min.js');
                $team_id = $_GET['team_id'];
                $team_data = get_team_by_id($team_id);
                $node->content['fgrteam'] = array(
                    "#markup" => theme('fgrteam', array('fgrteam' => $team_data, 'node' => $node, 'crumbs' => $crumbs))
                );
            } else {
                $result = get_fgr_teams();
                $node->content['fgrteam_list'] = array(
                    "#markup" => theme('fgrteam_list', array('fgrteam_list' => $result, 'node' => $node, 'crumbs' => $crumbs))
                );
            }
            break;
    }
}

/**
 * Implements hook_theme();
*/
function fgrteam_theme() {
    return array(
        'fgrteam_list' => array(
            'variables' => array('fgrteam_list' => NULL, 'node' => NULL, 'crumbs' => NULL),
            'template' => 'templates/fgrteam-list',
            'file' => 'fgrteam.pages.inc',
        ),
        'fgrteam' => array(
            'variables' => array('fgrteam' => NULL, 'node' => NULL, 'crumbs' => NULL),
            'template' => 'templates/fgrteam',
            'file' => 'fgrteam.pages.inc',
        )
    );
}