<?php

/**
 * @file
 * A block module that displays recent blog and forum posts.
 */
function fgrteam_help($path, $arg) {
  switch ($path) {
    case "admin/help#fgrteam":
      return '' . t("Displays fgr teams") . '';
      break;
  }
}

/**
 * Implements hook_node_info().
 */
function fgrteam_node_info() {
  $items = array(
      'fgrteam' => array(
          'name' => t('FGR team'),
          'base' => 'node_content',
          'description' => t('Displays FGR team.'),
          'help' => 'Displays FGR team.',
      ),
  );
  return $items;
}

/**
 * Implements hook_node_view().
 */
function fgrteam_node_view($node, $view_mode, $langcode)
{
    module_load_include('inc', 'fgrteam', 'fgrteam.api');
    switch ($node->type) {
        case 'fgrteam':
            if(isset($_GET['team_id'])) {
                drupal_add_js(drupal_get_path('module', 'fgrteam') . '/js/sorttable.js');
                drupal_add_js(drupal_get_path('module', 'fgrteam') . '/js/jquery-ui.min.js');
                $team_id = $_GET['team_id'];
                $team_data = get_team_by_id($team_id);
                $team_games_markup = theme('fgrteam_games', array('fgrteam_games' => get_last_team_games($team_id), 'node' => $node));
                $node->content['fgrteam'] = array(
                    "#markup" => theme('fgrteam', array('fgrteam' => $team_data, 'node' => $node)) . $team_games_markup
                );
            } else {
                $result = get_fgr_teams();
                $node->content['fgrteam_list'] = array(
                    "#markup" => theme('fgrteam_list', array('fgrteam_list' => $result, 'node' => $node))
                );
            }
            break;
    }
}

/**
 * Implements hook_theme();
*/
function fgrteam_theme() {
    return array(
        'fgrteam_list' => array(
            'variables' => array('fgrteam_list' => NULL, 'node' => NULL, 'crumbs' => NULL),
            'template' => 'templates/fgrteam-list',
            'file' => 'fgrteam.pages.inc',
        ),
        'fgrteam' => array(
            'variables' => array('fgrteam' => NULL, 'node' => NULL, 'crumbs' => NULL),
            'template' => 'templates/fgrteam',
            'file' => 'fgrteam.pages.inc',
        ),
        'fgrteam_games' => array(
            'variables' => array('fgrteam_games' => NULL, 'node' => NULL),
            'template' => 'templates/fgrteam-games',
            'file' => 'fgrteam.pages.inc',
        )
    );
}